In [16]:
import numpy as np
np.__version__

'2.4.2'

In [17]:
ls  = [[[1, 2, 3]]]
arr = np.array(ls)
type(arr)

numpy.ndarray

In [18]:
# dimension of the array

arr.ndim

3

In [19]:
arr.size

3

In [20]:
arr.shape

(1, 1, 3)

In [21]:
np.array([12, 43, 23, 2.5])

array([12. , 43. , 23. ,  2.5])

In [22]:
np.array([12, 43, 23, 2.5, 2+5j])

array([12. +0.j, 43. +0.j, 23. +0.j,  2.5+0.j,  2. +5.j])

In [23]:
np.array([12, 43, 23, 2.5], dtype = 'int')

array([12, 43, 23,  2])

In [24]:
np.array([12, 43, 23, 2.5], dtype = 'float')

array([12. , 43. , 23. ,  2.5])

In [25]:
np.array([12, 43, 23, 2.5], dtype = 'str')

array(['12', '43', '23', '2.5'], dtype='<U3')

In [26]:
np.array([12, 43, 23, 2.5, 2+5j], dtype = 'complex')

array([12. +0.j, 43. +0.j, 23. +0.j,  2.5+0.j,  2. +5.j])

In [29]:
new_arr = np.array([[12, 43, 23],
                   [2, 43, 23],
                   [120, 43, 23]])
new_arr

array([[ 12,  43,  23],
       [  2,  43,  23],
       [120,  43,  23]])

In [31]:
np.array([[12, 43, 23],
         [2, 43, 23], 
         [120, 43, np.nan]])

array([[ 12.,  43.,  23.],
       [  2.,  43.,  23.],
       [120.,  43.,  nan]])

In [32]:
np.array([[12, 43, 23],
         [2, 43, 23], 
         [120, 43, None]])

array([[12, 43, 23],
       [2, 43, 23],
       [120, 43, None]], dtype=object)

In [38]:
# list(range(1.5, 11.5)) # 'range' will not work for float values

In [39]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
np.arange(1.5, 11.5)

array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5])

In [44]:
np.arange(1.5, 11.5, 2)

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [48]:
arr = np.array([[1, 2, 3], 
               [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
arr.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
arr.reshape(1, 6)

array([[1, 2, 3, 4, 5, 6]])

In [54]:
arr = np.array([[[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]]])
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [55]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [61]:
np.ones([2, 3], dtype = 'int')

array([[1, 1, 1],
       [1, 1, 1]])

In [68]:
np.zeros([2, 3, 4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [69]:
np.full(10, 7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [70]:
np.full([2, 3], 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [71]:
np.full([2, 3],
        [7, 8, 9])

array([[7, 8, 9],
       [7, 8, 9]])

In [72]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.randint(1, 10, 5)
# here range is 1 - 10  & elements will be 5

array([6, 3, 6, 6, 4], dtype=int32)

In [ ]:
np.random.randint(1, 101) 
# here range is 1 - 101

85

In [207]:
np.random.randint(3, 200, 20)

array([183, 115,  10, 162, 198,  67, 183, 185, 110,  74, 119,  69, 143,
       123,  19,  91, 147,  75,  63,  60], dtype=int32)

In [208]:
np.random.randint(100, 200, [3, 4])

array([[160, 186, 168, 109],
       [188, 162, 178, 121],
       [167, 108, 197, 190]], dtype=int32)

In [209]:
np.random.rand(5)

array([0.41556461, 0.17219099, 0.37992128, 0.46210641, 0.31223547])

In [210]:
np.random.rand(1, 10, 5)

array([[[0.68585816, 0.17785462, 0.3670273 , 0.99293373, 0.76281253],
        [0.54501276, 0.39485006, 0.95923614, 0.88950022, 0.66189802],
        [0.24011823, 0.01972338, 0.6768892 , 0.48361511, 0.64650743],
        [0.12727009, 0.04010868, 0.33075958, 0.62924655, 0.86278358],
        [0.52741995, 0.51873181, 0.4882526 , 0.96083089, 0.91715354],
        [0.89178527, 0.8088272 , 0.83485179, 0.20856719, 0.84104433],
        [0.88680067, 0.90442941, 0.30176802, 0.01508311, 0.39016766],
        [0.37881497, 0.01069428, 0.94024519, 0.4188704 , 0.73700358],
        [0.61653589, 0.82801384, 0.54256011, 0.67046171, 0.63528169],
        [0.82351072, 0.67804466, 0.37571205, 0.6326513 , 0.02438209]]])

In [220]:
np.random.randn(5)

array([ 0.38592568, -1.01605345,  0.46826813, -0.40692627,  0.85717619])

In [224]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [225]:
np.linspace(2, 5)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [ ]:
np.linspace(2, 5, )

In [228]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [229]:
arr = np.arange(1, 11).reshape(2, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### **Copy and View** ####

In [230]:
new_arr = arr.view()
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [231]:
new_arr_copy = arr.copy()
new_arr_copy

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [232]:
arr[0][0] = 1000
arr

array([[1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10]])

In [233]:
new_arr_copy

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])